name: Re:dash Updates
description: Updates on the project progress.
meta_description: "Updates, version releases and more."

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://blog.redash.io'
google_analytics: 'UA-47088186-5'

# Details for the RSS feed generator
url:            'blog url'
author:         'Arik Fraimovich'
