name: Re:dash Updates
description: Re:dash news and updates.
meta_description: "Updates, version releases and more."

logo: true
paginate: 15
baseurl: /
domain_name: 'http://blog.redash.io'
google_analytics: 'UA-47088186-5'

# Details for the RSS feed generator
url: 'http://blog.redash.io'
author:         'Arik Fraimovich'
